### PR TITLE
Anthony dev

### PR DESCRIPTION
**Pull request by anthonysingiser**
-change layout to components
-add ItemList and ItemForm components
-add axios and react-router-dom
-create Dashboard page 
-add routing to App.jsx

### CODE REVIEW

**Review by abcamuez — COMMENTED** [review]
Everything looks good.

**Review by abcamuez — APPROVED** [review]

**Review by Kayboy4140 — COMMENTED** [review]
I see that you included a /dashboard path. I believe that should lead to the dashboard but it is displaying an empty page. Is this different from your side or you are still working to populate that page?

**Comment by anthonysingiser** [comment]
I am now working to populate that page. We currently have a Dashboard page structure with the necessary tools (axios / react-router-dom) and I am currently working on connecting that to the backend so that it will populate / interact with sql server.

**Comment by Kayboy4140** [comment]
Awesome!

**Pull request merged**
