### PR TITLE
Search recipes by query

### PR DESCRIPTION
**Pull request by abcamuez**
- Added a Shopping List & Shopping List Item entity
- Made a simple search query for recipes(did not add any filters)
- Added the API key
- Added a notebook image to the dashboard.( still need to adjust the image properties and margins)

### CODE REVIEW

**Review by anthonysingiser — APPROVED** [review]
good work

**Comment by Kayboy4140** [comment]
> good work

I know you approved this already. Did you try to run the back end before approving? Because my backend is breaking upon merging in the code changes

**Comment by anthonysingiser** [comment]
sorry about this Kayode, I thought I could merge the commit? I merged the whole thing. Either way I was having the same trouble and it seems that the issue is that we need the Entity imports and annotation in the ShoppingList and ShoppingListItem entity classes. I'll follow up with another merge request.

**Comment by Kayboy4140** [comment]
No problem. Just wanted to be sure it was not happening at my own end only. I couldn't get the login and registration page to work rightly as well. It is saying registration and login failed. Are you having similar issues as well?

**Pull request merged**
